#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
ArteBox : Gestionnaire de télachargements pour Arte+7
"""

__author__ = "wlourf"
__email__ = "wlourf1@yahoo.com"
__description__ = "Téléchargements arte+7"

__license__ = """

Artebox, Arte+7 downloader

This file is part of ArteBox.

Mirage is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Mirage is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import artebox

if __name__ == "__main__":
    app = artebox.Base()
    try:
        app.main()
    except KeyboardInterrupt:
        pass


